"""Pydantic schemas for structured caption and critic outputs."""

from pydantic import BaseModel, Field


class CaptionSet(BaseModel):
    """Four distinct caption styles generated by the copywriter agents."""

    formal: str = Field(..., description="Professional, polished caption suitable for corporate or press use.")
    sarcastic: str = Field(..., description="Dry, witty caption with subtle irony.")
    humorous_tech: str = Field(..., description="Tech-savvy humor with insider jargon and memes.")
    humorous_non_tech: str = Field(..., description="Accessible humor for a general audience.")


class CriticEvaluation(BaseModel):
    """Structured output from the critic agent after reviewing all caption styles."""

    captions: CaptionSet
    tonal_scores: dict[str, float] = Field(
        ...,
        description="Per-style tonal alignment scores from 0.0 to 1.0.",
    )
    critique_notes: str = Field(..., description="Detailed feedback on caption quality and tone.")
    approved: bool = Field(..., description="Whether all captions meet quality and tonal standards.")
